- name: Add Kubernetes package key
  rpm_key: 
    key: https://packages.cloud.google.com/yum/doc/yum-key.gpg

- name: Add Kubernetes repo
  yum_repository:
    name: Kubernetes
    description: Kubernetes repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgkey: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    gpgcheck: yes

- name: Install Kubernetes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - kubelet
    - kubectl
    - kubernetes-cni

- name: Start kubelet service
  systemd:
    name: kubelet
    enabled: yes
    state: started
    daemon_reload: yes

