- name: Add docker repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_lsb.id }} {{ ansible_lsb.codename }} stable

- name: Install docker
  apt:
    name: docker-ce
    update_cache: yes
