- name: Copy node_exporter to /usr/bin
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
    dest: /usr/bin
    creates: /usr/bin/node_exporter

- name: Configure node_exporter.service as a service
  copy:
    src: node_exporter.service
    dest: /etc/init.d/node_exporter
    owner: root
    group: root
    mode: 0755

- name: Enable and Start node_exporter service
  service:
    name: node_exporter
    enabled: yes
    state: started
